import Head from "next/head";
import PropTypes from "prop-types";
import style from "@/styles/Home.module.scss";
import Contact from "@/components/views/home/contact/Contact";
import Gallery from "@/components/views/home/gallery/Gallery";
import Hero from "@/components/views/home/hero/Hero";
import Chef from "@/components/views/home/chef/Chef";
import About from "@/components/views/home/about/About";
import Menu from "@/components/views/home/menu/Menu";
import Video from "@/components/views/home/video/Video";
import Award from "@/components/views/home/award/Award";

export default function Home() {
  return (
    <>
      <Head>
        <title>Gericht | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <Hero />
        <About />
        <Menu />
        <Chef />
        <Video />
        <Award />
        <Gallery />
        <Contact />
      </main>
    </>
  );
}

Home.propTypes = {};
