import Head from "next/head";
import PropTypes from "prop-types";
import style from "@/styles/Home.module.scss";
import Contact from "@/components/views/Contact";
import Gallery from "@/components/views/Gallery";
import Hero from "@/components/views/Hero";
import Chef from "@/components/views/Chef";
import About from "@/components/views/About";
import Menu from "@/components/views/Menu";
import Video from "@/components/views/Video";
import Award from "@/components/views/Award";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <Hero />
        <About />
        <Menu />
        <Chef />
        <Video />
        <Award />
        <Gallery />
        <Contact />
      </main>
    </>
  );
}

Home.propTypes = {};
