import Head from "next/head";
import PropTypes from "prop-types";
import ApiService from "@/services/ApiService";
import style from "@/styles/Menu.module.scss";
import { useQuery } from "react-query";
import Hero from "@/components/views/menu/hero/Hero";

export default function Menu() {
  const api = new ApiService();
  const { data, error } = useQuery(["meal"], () =>
    api.getByCategory("chicken")
  );

  return (
    <>
      <Head>
        <title>Gericht | Menu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.main}>
        <Hero />
      </main>
    </>
  );
}

Menu.propTypes = {};
